language: node_js
node_js:
  - "6"
env:
  - BUILD_DIR="../w20-ghp"
  - FONTFID="0B4ooUkEfVrhlbHJ5aGZTcVV5bUU"
install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs.tar.bz2 -C $PWD/travis-phantomjs --strip-components=1
  - export PATH=$PWD/travis-phantomjs/bin:$PATH
  - wget "https://drive.google.com/uc?export=download&id=$FONTFID" -O fonts-humla.tar.gz
  - tar xvzf fonts-humla.tar.gz
  - sudo mv fonts-humla /usr/share/fonts/
  - sudo fc-cache -f -v  
script:
  - rm -rf $BUILD_DIR
  - git clone https://$GITHUB_TOKEN@github.com/tomvit/w20.git $BUILD_DIR
  - cd $BUILD_DIR
  - git submodule update --init --recursive 
  - git config --global user.email "travis"
  - git config --global user.name "travis"
  - git checkout gh-pages
  - git fetch 
  - git merge origin/master --no-commit || true
  - export COURSE_HOME=$(pwd)
  - $COURSE_HOME/humla/bin/create-toc.sh
  - $COURSE_HOME/humla/bin/generate-pdfs.sh
  - git add -A .
  - git commit -a -m "Travis build $TRAVIS_BUILD_NUMBER" || true
  - git push --quiet origin gh-pages > /dev/null 2>&1
